next_address_book_contact_list:
    path:     /
    defaults: { _controller: NextAddressBookBundle:Contact:list }

next_address_book_contact_add:
    path:     /add
    defaults: { _controller: NextAddressBookBundle:Contact:add }

next_address_book_contact_show:
    path:     /{id}
    defaults: { _controller: NextAddressBookBundle:Contact:show }
    requirements:
        id: "[1-9][0-9]*"

next_address_book_contact_delete:
    path:     /{id}/delete
    defaults: { _controller: NextAddressBookBundle:Contact:delete }
    requirements:
        id: "[1-9][0-9]*"

next_address_book_contact_modify:
    path:     /{id}/modify
    defaults: { _controller: NextAddressBookBundle:Contact:modify }
    requirements:
        id: "[1-9][0-9]*"
